version: "2.4"
volumes:
  config: {}
services:
  homeassistant:
    build:
      context: homeassistant
    ports:
      - "51827:51827"
      - "80:8123"
    expose:
      - 51827
    devices:
      - "/dev:/dev"
    restart: always
    volumes:
      - "config:/config"
    privileged: true
    network_mode: host
